# Generated by Django 5.1.7 on 2025-07-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                help_text="Enter the book's natural language", max_length=200
            ),
        ),
    ]
