# Generated by Django 5.1.7 on 2025-07-17 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_language_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                help_text="Select a genre for this book", to="catalog.genre"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="13 Character ISBN number",
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(
                help_text="Enter a brief description of the book", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
