# Generated by Django 5.1.7 on 2025-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_bookinstance_borrower_alter_book_genre_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={"permissions": (("can_mark_returned", "Set book as returned"),)},
        ),
    ]
